---
- name: Configure splunk deployment server port
  command: '{{dir_home_splunk}}/bin/splunk set deploy-poll {{splunk_deployment_server}}:{{splunk_server_port}} -auth'

- name: Configure splunk forwarder port
  command: '{{dir_home_splunk}}/bin/splunk add forward-server {{splunk_deployment_server}}:{{splunk_indexer_port}} -auth'
...
