---
- name: Setup Splunk user
  user:
    name: '{{user_splunk}}'
    home: '{{dir_home_splunk}}'
    
- name: Download Splunk Forwarder package
  get_url:
    url: '{{splunk_forwarder_download_url}}'
    dest: '/opt/splunkforwarder/{{package_name_forwarder}}'
    mode: '0664'

- name: Install Splunk Forwarder package for RHEL | CentOS | AlmaLinux
  shell: 'rpm -i {{dir_home_splunk}}/{{package_name_forwarder}}'

- name: Change ownership of Splunk Forwarder directory
  file:
    state: 'directory'
    recurse: true
    path: '{{dir_home_splunk}}'
    owner: '{{user_splunk}}'
    group: '{{user_splunk}}'

- name: Start the Splunk Forwarder
  expect:
    command: '{{dir_home_splunk}}/bin/splunk start --accept-license'
    responses:
      (?i).*username.*: "{{splunk_admin_user}}"
      (?i).*password.*:
      - "{{splunk_admin_pass}}"
      - "{{splunk_admin_pass}}"
  no_log: true

- name: Enable the Splunk Forwarder at boot
  shell: '{{dir_home_splunk}}/bin/splunk enable boot-start -systemd-managed 0'
...
