---
- name: Setup Splunk user
  user:
    name: '{{user_splunk}}'
    home: '{{dir_home_splunk}}'
    
- name: Download Splunk Forwarder package
  get_url:
    url: '{{splunk_forwarder_download_url}}'
    dest: '/opt/splunkforwarder/{{package_name_forwarder}}'
    mode: '0664'

- name: Install Splunk Forwarder package for RHEL | CentOS | AlmaLinux
  shell:
    command: 'yum install '{{dir_home_splunk}}/{{package_name_forwarder}}'

- name: Change ownership of splunkforwarder directory
  file:
    state: 'directory'
    recurse: true
    path: '{{dir_home_splunk}}'
    owner: '{{user_splunk}}'
    group: '{{user_splunk}}'

- name: Start the splunkforwarder
  shell:
    command: '{{dir_home_splunk}}/bin/splunk start'
...
