---
- name: Setup Splunk user
  user:
    name: '{{user_splunk}}'
    home: '/opt/splunkforwarder/'
    
- name: Download Splunk Forwarder package
  get_url:
    url: '{{splunk_forwarder_download_url}}'
    dest: '/opt/splunkforwarder/{{package_name_forwarder}}'
    mode: '0664'

- name: Install Splunk Forwarder package for RHEL | CentOS | AlmaLinux
  shell:
    command: 'yum install /opt/splunkforwarder/{{package_name_forwarder}}'

- name: Change ownership of splunkforwarder directory
  file:
    state: 'directory'
    recurse: true
    path: '/opt/splunkforwarder'
    owner: 'splunk'
    group: 'splunk'

- name: Start the splunkforwarder
  shell:
    command: '/opt/splunkforwarder/bin/splunk start'
