---
- name: Install dependencies
  include_tasks: dependencies.yml
  
- name: Install Splunk Forwarder
  include_tasks: install.yml
    
- name: Configure Splunk Forwarder
  include_tasks: config.yml
  when: config_splunk_forwarder | bool
...
