---
- name: Install Requirements
  include_tasks: requirements.yml
  
- name: Install Splunk Forwarder
  include_tasks: install.yml
    
- name: Configure splunk forwarder
  include_tasks: config.yml
  when: config_splunk_forwarder | bool
...
