---
- name: Install dependencies
  include_tasks: dependencies.yml

- name: Gather package_facts
  package_facts:

- name: Install Splunk Forwarder
  include_tasks: install.yml
  when:
  - "'splunkforwarder' not in ansible_facts.packages|lower"
  
- name: Configure Splunk Forwarder
  include_tasks: config.yml
  when: config_splunk_forwarder | bool

- name: Restart Splunk Forwarder
  command: '{{dir_home_splunk}}/bin/splunk restart'
...
